version: '3'

services:
  web:
    container_name: book_list_web_container
    build: 
      context: ./web
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Tokyo"
    ports:
        - "8088:80"
    volumes:
      - type: bind
        source: ../app
        target: /var/www/html
    networks:
      - book_list_network
  db:
    container_name: book_list_mysql_db_container
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: kisara
      MYSQL_PASSWORD: kazuma
      MYSQL_DATABASE: booklist
    ports:
      - "3306:3306"
    networks:
      - book_list_network
    volumes:
      - type: volume
        source: book_list_db_volume
        target: /var/lib/mysql
      - type: bind
        source: ./db/init
        target: /docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  # command: mysqld --log-output=FILE --general-log=1 --general-log-file=/path/to/mysql_general.log --log-bin=/path/to/mysql_bin.log --binlog-format=MIXED
  # command: mysqld --log-output=FILE --general-log=1 --general-log-file=/var/log/mysql/mysql_general.log --log-bin=/var/log/mysql/mysql_bin.log --binlog-format=MIXED
networks:
  book_list_network:

volumes:
  book_list_db_volume:
    driver: local  
